# Amazon Web Services (AWS)


## Access Key ID y Secret Key 

1. Logearte en tu consola de AWS - [AWS Management Console](https://aws.amazon.com/console/)

2. Dar click a la parte superior derecha donde está tu nombre de cuenta.
3. Dar click en "Security Credentials".
4. Dar click en "Access Keys (Access Key ID and Secret Access Key)"
5. Dar click en "Create new Access Key"

Estas llaves son sumamente importantes.  Son los accesos a tu cuenta de AWS.
Guardenlas en algun pinche lugar bien mamón, metenla en la carpeta de la carpeta de la carpeta,
escribanla en un post-it y metanla en algun pinche libro que te regalaron que jamás vayas a leer.
Y no la pinches vayan a subir al github!!!

Las vamos a usar al configurar aws desde la terminal:)

##Instalación de AWS Command Line Interface en tu computadora

AWS Command Line Interface, alias "awscli"  es el programita que sirve como 
interfaz entre tu computadora y los servicios de AWS. Nos permitirá conectarnos desde la terminal


Abre tu terminal y teclea:
```
pip install awscli
```
Al terminar de instalarse vamos a configurar algunas cosas basicas. Te pedirá 
Tus "Access Keys", tenlas a la mando en el archivo que se baja. 

```
aws configure

AWS Access Key ID [****************]: COPY-PESTEA tu llave
AWS Secret Access Key [****************]: COPY-PESTEA tu llave
Default region name [us-west-2]: us-east-1 
Default output format [None]: ENTER
```
***Nota** 
Amazon tiene varios hosts alrededor del mundo. Escogemos us-east-1 por que es el 
que provee más servicios, pero pueden escoger el que quieran.
Para más información de los servidores ->
[Regions and Availability Zones](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-regions-availability-zones)

LISTO muchachachit@s ... falta más

## Crear un Bocket en S3
Vamos a crear un bocket en S3 que es una especie de carpeta en dónde se va a contener todo para nuestra arquitectura.

S3 es el el servicio de cloud storage de nuestro muchacho el pelon-pelorico de Jeff Bezos.
Si quieren nerdear, entrar al siguiente link, hay un videito bien cagado:
[Amazon S3](https://aws.amazon.com/s3/)

Entramos en la consola desde tu browser favorito... (Internet Explorer...not]) 
Se puede hacer desde la terminal, pero eeeeehh.
[AWS Management Console](https://aws.amazon.com/console/)

1. Logearte en tu consola de AWS - [AWS Management Console](https://aws.amazon.com/console/)

2. Dar click en el iconito S3 de color rojo abajo de donde dice "Storage & Content Delivery, primera columna" -> no mamen si no lo encuentran
3. Dar click en "Create a Bucket".
4. Pongan el nombre de su proyecto. 
  Lo pinche es que cada bucket es unico y solo pueden poner un nombre que nadie más haya usado en el mundo... de la verga no?

... sharan!!!
Ya tienen su bucket. 

**Nota**
Ya estando aquí pueden darle click a la carpeta y en "Actions" pueden subir sus bases de datos. 
-> como por ejemplo la de los ovnis que vimos en clase.



Desde la terminal tiren:
```
aws s3 ls
```
Les debe de aparecer algo asi:

```
2016-04-13 13:58:19 clase-dpa
```

Si no les dio error es que ya chingaron... 
Si no, es por que seguramente todavia no tienen configurado el SSH para conectarse desde su compu.
Les va a dar error, porque todavía no hemos ligado nuestra compu a ninguna estancia en la "nube" del señor Bezos.

## EC2
La idea es ser capaz de conectarnos desde nuestra terminal a las instancias (maquinas) que abramos en EC2.
***Nota***
Si quieren nerdear por segunda vez, entrar al siguiente link, hay otro videito:
[Amazon EC2](https://aws.amazon.com/ec2/)

##Key Pair
Vamos a crear una llave que encripta y desencripta tu loggin. 


Desde la consola de AWS 
1. Dar click al iconito de EC2 (este es naranja).
2. En la columna izquierda, hay varias opciones. Localiza la que dice en gris "Network & Security"
3. Dar click en "Key Pairs".
4. Dar click en el ícono azul que dice "Create Key Pair"
5. Pongale un nombre y se descargara un ".pem" en su compu.

*** NOTA Con este certificado podrán logearse a sus instancias que tienen en cada server. 
Si se mueven de server a otra región tienen que sacar otro de esa región.

El archivo .pem hay que moverlo a la carpeta .ssh de su compu.

Desde la carpeta donde hayan bajado su archivo .pem tiren 
```
mv file.pem  /Users/USUARIO/.ssh
```

verificamos que este aqui
```
cd ~ && cd .ssh && ls
```

Ahora hay que modificar el archivo config 
```
nano ~/.ssh/config
```
Pongan el siguiente texto:
```
Host *.amazonaws.com
  IdentityFile ~/.ssh/schzcas.pem
  User ubuntu
```
***NOTA***
Ponemos usuario ubuntu por que asumismos que nuestras instancias estarán levantadas en ubuntu.

Para los usuarios de MAC o Linux tiren:
```
 chmod 400 ***my-key-pair***.pem
 ```

cd .ssh
ls -la
chmod 400 schzcas.pem
 history 20
nano ~/.ssh/config
aws ec2 describe-instances | jq '.Reservations[].Instances[] |  {PublicDnsName, InstanceId, PublicIpAddress}'
awclis ec2 describe-instances | jq '.Reservations[].Instances[] |  {PublicDnsName, InstanceId, PublicIpAddress}'
awscli ec2 describe-instances | jq '.Reservations[].Instances[] |  {PublicDnsName, InstanceId, PublicIpAddress}'
pip install jq
brew install jq
awscli ec2 describe-instances | jq '.Reservations[].Instances[] |  {PublicDnsName, InstanceId, PublicIpAddress}'
cd ..
pwd
aws ec2 describe-instances | jq '.Reservations[].Instances[] |  {PublicDnsName, InstanceId, PublicIpAddress}'
history
history 34
cd Desktop/
ll
history 36 >aws.txt
 